# Site settings

title: Florian Oswald
email: florian.oswald@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SciencesPo, Dept of Economics <br>
  28 Rue des Saints-Pères <br>
  75007 Paris  <br>
  France
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://floswald.github.io" # the base hostname & protocol for your site
twitter_username: FlorianOswald
github_username:  floswald

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# other options
# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""